Repository C-KLex/GymBro, pull requests merged in 2023-06, with the labels that each got.

#29 Refactor RoutineExerciseView
  GymBro.xcodeproj/project.pbxproj
  GymBro/Views/RoutineViews/AddExerciseButton.swift
  GymBro/Views/RoutineViews/EditSetView.swift
  GymBro/Views/RoutineViews/RExer_AdExerShe_AddNewExerciseSheet.swift
  GymBro/Views/RoutineViews/RExercise_AddExerciseSheet.swift
  GymBro/Views/RoutineViews/RExercise_SetRow.swift
  GymBro/Views/RoutineViews/RExercise_SetRow_EditSetSheet.swift
  GymBro/Views/RoutineViews/RoutineExerciseView.swift
Labels: refactor

#28 Setting view's brief view
  GymBro.xcodeproj/project.pbxproj
  GymBro/Assets.xcassets/BackGround.colorset/Contents.json
  GymBro/Assets.xcassets/ForeGround Title.colorset/Contents.json
  GymBro/Extensions.swift
  GymBro/GymBroApp.swift
  GymBro/Views/SettingViews/MainSettingView.swift
  GymBro/Views/SettingViews/SettingView_ExportDataView.swift
  GymBro/Views/SettingViews/SettingView_HelpCenterView.swift
  GymBro/Views/SettingViews/SettingView_NotificationSettingView.swift
  GymBro/Views/SettingViews/SettingView_RateTheAppView.swift
  GymBro/Views/SettingViews/SettingView_ReportIssueSheet.swift
Labels: enhancement

#30 RoutineExerciseView into VM
  GymBro.xcodeproj/project.pbxproj
  GymBro/Views/RoutineViews/RExer_AdExerShe_AddNewExerciseSheet.swift
  GymBro/Views/RoutineViews/RExercise_AddExerciseSheet.swift
  GymBro/Views/RoutineViews/RExercise_SetRow.swift
  GymBro/Views/RoutineViews/RExercise_SetRow_AddSetSheet.swift
  GymBro/Views/RoutineViews/RExercise_SetRow_UpdateSetSheet.swift
  GymBro/Views/RoutineViews/RoutineExerciseView.swift
Labels: enhancement, refactor

#33 Chart view's first PR
  GymBro.xcodeproj/project.pbxproj
  GymBro/Extensions.swift
  GymBro/Views/ChartViews/MainChartView.swift
Labels: enhancement

#34 feat: add alert in RoutineExerciseView
  GymBro.xcodeproj/project.pbxproj
  GymBro.xcodeproj/xcshareddata/xcschemes/GymBro.xcscheme
  GymBro/Views/RoutineViews/RExercise_AddExerciseSheet.swift
  GymBro/Views/RoutineViews/RoutineExerciseView.swift
Labels: enhancement
